using MomoAI.Application.DTOs;

namespace MomoAI.Application.Interfaces;

/// <summary>
/// Gateway interface for communicating with OpenAI API for response generation.
/// Handles timeouts (30s), retries (3 attempts with exponential backoff),
/// and fallback responses on total failure.
/// </summary>
public interface IAIGateway
{
    /// <summary>
    /// Generates an AI response based on the provided request.
    /// </summary>
    /// <param name="request">The AI request containing system prompt, user message, and context.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>The AI response with generated text, detected emotion, and sentiment score.</returns>
    Task<AIResponse> GenerateAsync(AIRequest request, CancellationToken ct);

    /// <summary>
    /// Generates a streaming AI response, yielding text chunks as they become available.
    /// Each chunk should be delivered to the caller within 300ms of generation.
    /// Falls back to non-streaming GenerateAsync if streaming is not supported.
    /// </summary>
    /// <param name="request">The AI request containing system prompt, user message, and context.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>An async enumerable of text chunks as they are generated by the AI model.</returns>
    IAsyncEnumerable<string> GenerateStreamingAsync(AIRequest request, CancellationToken ct);
}
